name: metrics
on:
  schedule: [{cron: "0 8 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          filename: spotify.svg
          token: ${{ secrets.GH_TOKEN }}
          user: Deoprag
          base: ""
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_mode: recent
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
          config_timezone: America/Sao_Paulo

      - uses: lowlighter/metrics@master
        with:
          filename: wakatime.svg
          token: ${{ secrets.GH_TOKEN }}
          user: Deoprag
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_token: ${{ secrets.WAKATIME_API_KEY }}
          plugin_wakatime_sections: time, languages, languages_graphs, editors, editors-graphs, os, os_graphs
          config_timezone: America/Sao_Paulo
